[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "IsingElectrolyte"        # what pip install sees
version = "0.1.0"
description = "Tools for fitting an Ising model for LHCE design"
authors = [
  { name = "Hancheng Zhao", email = "zhaohc@umich.edu" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" } 

# Your runtime dependencies (example)
dependencies = [
  "jax",
  "optax",
  "numpy",
  "pandas",
  "scipy",
  "matplotlib",
  "jaxopt",
  "scikit-learn",
  "tqdm",
]

[project.optional-dependencies]
dev = [
  "pytest",
]

[project.urls]
repository="https://github.com/hancheng2000/IsingElectrolyte.git"
issues="https://github.com/hancheng2000/IsingElectrolyte/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
